# Generated by Django 4.2.28 on 2026-03-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duty_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duty_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invigilator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv1', to='duty.faculty')),
                ('invigilator2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv2', to='duty.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.room')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.shift')),
            ],
        ),
    ]
