# Generated by Django 4.2.28 on 2026-03-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='invigilator2',
        ),
        migrations.AddField(
            model_name='duty',
            name='invigilator2_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator2_faculty', to='duty.faculty'),
        ),
        migrations.AddField(
            model_name='duty',
            name='invigilator2_labtech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator2_labtech', to='duty.labtech'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='invigilator1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator1', to='duty.faculty'),
        ),
    ]
