# Generated by Django 4.2.28 on 2026-03-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_remove_duty_invigilator2_duty_invigilator2_faculty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='duty_count',
        ),
        migrations.RemoveField(
            model_name='labtech',
            name='duty_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='2026-01-01', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duty',
            name='invigilator1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv1', to='duty.faculty'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='invigilator2_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv2_faculty', to='duty.faculty'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='invigilator2_labtech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv2_labtech', to='duty.labtech'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(max_length=50),
        ),
    ]
