# Generated by Django 4.2.29 on 2026-03-10 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_course_semester_subject_shift_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_date',
            field=models.DateField(default=datetime.date(2026, 3, 11)),
            preserve_default=False,
        ),
    ]
