# Generated by Django 4.2.29 on 2026-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0006_subject_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam_date',
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20),
        ),
    ]
